version: "3.8"

services:
  server:
    image: docker.gitea.com/gitea:1.23.8
    volumes:
      - /mnt/gluster/slowpool/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: ${DB_HOST}:${DB_PORT}
      GITEA__database__NAME: ${DB_NAME}
      GITEA__database__USER: ${DB_USER}
      GITEA__database__PASSWD: ${DB_PASS}
    networks:
      - gitea_internal
      - public_network
    ports:
      - "222:22"
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        failure_action: rollback

  db:
    image: docker.io/library/mysql:8.0.42
    volumes:
      - /mnt/gluster/fastpool/gitea:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      - gitea_internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        failure_action: rollback

networks:
  gitea_internal:
    driver: overlay
    internal: true
  public_network:
    external: true